# Generated by Django 6.0 on 2025-12-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='English name (internal, optional)', max_length=100, null=True)),
                ('name_ru', models.CharField(help_text='Russian display name (required)', max_length=100)),
                ('description_ru', models.TextField(blank=True, help_text='Category description in Russian (optional)', null=True)),
                ('order', models.IntegerField(blank=True, help_text='Display order (not used, categories ordered by PK)', null=True)),
            ],
            options={
                'verbose_name': 'Breathing Category',
                'verbose_name_plural': 'Breathing Categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BreathingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(help_text='Display name in Russian', max_length=200)),
                ('inhale', models.IntegerField(help_text='Inhale duration (seconds)')),
                ('hold_start', models.IntegerField(help_text='Hold after inhale (seconds)')),
                ('exhale', models.IntegerField(help_text='Exhale duration (seconds)')),
                ('hold_end', models.IntegerField(help_text='Hold after exhale (seconds)')),
                ('recommended_time_min', models.IntegerField(help_text='Total session duration (minutes)')),
                ('posture_ru', models.CharField(help_text="Quick preparation cue (e.g., 'Сидя')", max_length=100)),
                ('breath_origin', models.CharField(choices=[('ABDOMEN', 'ABDOMEN'), ('CHEST', 'CHEST'), ('NOSTRILS', 'NOSTRILS'), ('MOUTH', 'MOUTH'), ('ALL', 'ALL')], help_text='Focus area: ABDOMEN, CHEST, NOSTRILS, MOUTH, or ALL', max_length=20)),
                ('instructions_ru', models.TextField(help_text='Detailed step-by-step instructions in Russian')),
                ('use_sound_cue', models.BooleanField(default=True, help_text='Default sound toggle state')),
                ('use_haptic_cue', models.BooleanField(default=True, help_text='Default vibration toggle state')),
                ('category', models.ForeignKey(help_text='Category this technique belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='breathe.breathingcategory')),
            ],
            options={
                'verbose_name': 'Breathing Technique',
                'verbose_name_plural': 'Breathing Techniques',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BreathingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(help_text='When the session started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the session ended (null if cancelled)', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Actual session duration in seconds', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether session was completed (vs cancelled)')),
                ('cycles_completed', models.IntegerField(blank=True, help_text='Number of breathing cycles completed', null=True)),
                ('sound_enabled', models.BooleanField(default=True, help_text='Whether sound cues were enabled')),
                ('vibration_enabled', models.BooleanField(default=True, help_text='Whether vibration cues were enabled')),
                ('user', models.ForeignKey(help_text='User who performed the session', on_delete=django.db.models.deletion.CASCADE, related_name='breathing_sessions', to=settings.AUTH_USER_MODEL)),
                ('technique', models.ForeignKey(help_text='Which breathing technique was used', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='breathe.breathingtechnique')),
            ],
            options={
                'verbose_name': 'Breathing Session',
                'verbose_name_plural': 'Breathing Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='breathingtechnique',
            index=models.Index(fields=['category'], name='breathe_bre_categor_a736b9_idx'),
        ),
        migrations.AddIndex(
            model_name='breathingsession',
            index=models.Index(fields=['user'], name='breathe_bre_user_id_e79a79_idx'),
        ),
        migrations.AddIndex(
            model_name='breathingsession',
            index=models.Index(fields=['technique'], name='breathe_bre_techniq_3d9b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='breathingsession',
            index=models.Index(fields=['started_at'], name='breathe_bre_started_213b1f_idx'),
        ),
    ]
