# Generated by Django 6.0 on 2025-12-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('RESIST', 'RESIST'), ('SMOKED', 'SMOKED'), ('SPORT', 'SPORT')], help_text='Type of activity: RESIST, SMOKED, or SPORT', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the activity was logged')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='tracker_act_user_id_cbf606_idx'), models.Index(fields=['timestamp'], name='tracker_act_timesta_91a730_idx')],
            },
        ),
    ]
